<a href="https://colab.research.google.com/github/matheo-angelo/IC/blob/main/ABIDE_phenotipic_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ABIDE I: Análise Exploratória de Dados

O objetivo deste documento é analisar os dados fenotípicos da base ABIDE, para observar como podem ser usados em predições futuras, bem como quais informações podem ser obtidas sobre o conjunto de pacientes estudados.

In [1]:
def get_data_path():
    try:
        import google.colab
        return '/content/drive/MyDrive/IC/ABIDE I/Phenotypic_data.csv'
    except ImportError:
        return 'project_data/Phenotypic_data.csv'

In [2]:
import pandas as pd

fenotipos = pd.read_csv(get_data_path())
fenotipos

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
0,CALTECH,51456,1,4,55.40,1,R,NaN,126.0,118.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
1,CALTECH,51457,1,4,22.90,1,Ambi,NaN,107.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
2,CALTECH,51458,1,1,39.20,1,R,NaN,93.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
3,CALTECH,51459,1,1,22.80,1,R,NaN,106.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
4,CALTECH,51460,1,1,34.60,2,Ambi,NaN,133.0,135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107,YALE,50624,1,3,11.08,2,R,NaN,90.0,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1108,YALE,50625,1,3,7.00,1,L,NaN,99.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1109,YALE,50626,1,3,11.08,1,L,NaN,61.0,66.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1110,YALE,50627,1,3,9.50,2,R,NaN,88.0,103.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1111,YALE,50628,1,3,14.42,1,R,NaN,77.0,72.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN

Como podemos ver, há 1112 pacientes analisados, e para cada um deles, há 73 colunas de dados fenotípicos, e uma mostrando o ponto de coleta dos dados.

In [3]:
pd.set_option('display.max_columns', None)
fenotipos.describe()

,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_SCORES,FIQ,VIQ,PIQ,ADI_R_SOCIAL_TOTAL_A,ADI_R_VERBAL_TOTAL_BV,ADI_RRB_TOTAL_C,ADI_R_ONSET_TOTAL_D,ADI_R_RSRCH_RELIABLE,ADOS_MODULE,ADOS_TOTAL,ADOS_COMM,ADOS_SOCIAL,ADOS_STEREO_BEHAV,ADOS_RSRCH_RELIABLE,ADOS_GOTHAM_SOCAFFECT,ADOS_GOTHAM_RRB,ADOS_GOTHAM_TOTAL,ADOS_GOTHAM_SEVERITY,SRS_VERSION,SRS_RAW_TOTAL,SRS_AWARENESS,SRS_COGNITION,SRS_COMMUNICATION,SRS_MOTIVATION,SRS_MANNERISMS,SCQ_TOTAL,AQ_TOTAL,OFF_STIMULANTS_AT_SCAN,VINELAND_RECEPTIVE_V_SCALED,VINELAND_EXPRESSIVE_V_SCALED,VINELAND_WRITTEN_V_SCALED,VINELAND_COMMUNICATION_STANDARD,VINELAND_PERSONAL_V_SCALED,VINELAND_DOMESTIC_V_SCALED,VINELAND_COMMUNITY_V_SCALED,VINELAND_DAILYLVNG_STANDARD,VINELAND_INTERPERSONAL_V_SCALED,VINELAND_PLAY_V_SCALED,VINELAND_COPING_V_SCALED,VINELAND_SOCIAL_STANDARD,VINELAND_SUM_SCORES,VINELAND_ABC_STANDARD,VINELAND_INFORMANT,WISC_IV_VCI,WISC_IV_PRI,WISC_IV_WMI,WISC_IV_PSI,WISC_IV_SIM_SCALED,WISC_IV_VOCAB_SCALED,WISC_IV_INFO_SCALED,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
count,1112.000000,1112.000000,1112.000000,1112.000000,1112.000000,370.000000,1077.000000,935.000000,953.000000,412.000000,412.000000,412.000000,331.000000,411.000000,535.000000,442.000000,417.000000,417.000000,378.000000,380.000000,317.000000,317.000000,317.000000,317.000000,269.000000,405.000000,64.000000,64.000000,64.000000,64.00000,64.000000,143.000000,58.000000,141.000000,184.000000,184.000000,184.000000,184.000000,184.000000,184.000000,184.000000,184.00000,184.000000,184.000000,184.000000,184.000000,184.000000,184.000000,184.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,1112.000000,101.000000,214.000000
mean,50752.684353,1.515288,-646.819245,17.048864,1.147482,-102.560892,-238.854968,-86.757219,-126.663169,-807.024272,-786.364078,-819.577670,-1024.199396,-485.703163,-520.145794,-600.411765,-644.093525,-616.369305,-1241.579365,-104.334211,-1632.630915,-1480.082019,-1377.615142,-1382.053628,-1411.468401,-935.390123,7.546875,10.000000,17.406250,10.37500,8.937500,-1318.482517,-323.637931,-4892.957447,-3904.809783,-3904.717391,-3903.978261,-3857.864130,-3904.135870,-3905.043478,-3903.777174,-3856.98913,-3905.391304,-3904.972826,-3903.646739,-3858.423913,-3747.065217,-3858.364130,-3912.021739,112.109091,106.618182,100.690909,96.690909,12.381818,11.818182,12.127273,11.636364,9.909091,11.545455,10.127273,10.363636,8.763636,9.890909,1.312050,-86.176535,-5597.902757
std,447.680666,0.499991,2461.828856,8.036419,0.354745,1273.177790,1841.858322,1389.584584,1518.469557,2760.138808,2721.758259,2756.365347,3041.186842,2154.203134,2229.652348,2400.010037,2464.395989,2422.393356,3304.352821,1021.902378,3711.949672,3559.898569,3466.638672,3464.851221,3489.497583,3004.424555,4.120909,7.690439,12.852915,7.54142,7.028005,3409.862857,1844.472964,5016.355037,4899.555341,4899.629774,4900.223734,4937.322994,4900.097095,4899.367456,4900.385564,4938.01920,4899.088142,4899.424603,4900.490625,4936.880188,5026.580694,4936.919839,4893.756479,17.142834,13.967543,15.143600,14.309894,3.094146,3.646870,3.103490,3.014555,3.187201,2.651472,3.232099,2.914610,2.821634,2.753266,0.463539,996.228820,4984.307763
min,50002.000000,1.000000,-9999.000000,6.470000,1.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,1.000000,0.000000,0.000000,0.00000,0.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.00000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,63.000000,79.000000,56.000000,68.000000,1.000000,1.000000,5.000000,4.000000,3.000000,7.000000,2.000000,2.000000,4.000000,1.000000,1.000000,-9999.000000,-9999.000000
25%,50354.750000,1.000000,0.000000,11.658575,1.000000,48.000000,98.000000,97.000000,96.000000,14.000000,11.000000,3.750000,2.000000,1.000000,3.000000,8.000000,2.000000,5.000000,0.000000,1.000000,4.000000,1.000000,7.000000,4.000000,1.000000,12.000000,4.750000,3.750000,8.000000,3.75000,2.750000,1.000000,11.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.00000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,100.000000,97.000000,92.500000,84.000000,11.000000,9.500000,10.000000,10.000000,7.000000,10.000000,7.500000,9.500000,7.000000,8.000000,1.000000,11.250000,-9999.000000
50%,50724.500000,2.000000,0.000000,14.660000,1.000000,75.000000,108.000000,108.000000,107.000000,20.000000,15.500000,6.000000,3.000000,1.000000,3.000000,11.000000,3.000000,7.000000,2.000000,1.000000,8.000000,2.000000,11.000000,7.000000,1.000000,42.000000,8.000000,7.500000,15.000000,8.00000,7.500000,8.000000,18.500000,0.000000,9.000000,9.000000,11.000000,72.000000,11.000000,10.000000,11.000000,76.00000,8.000000,9.000000,11.000000,69.000000,222.000000,72.000000,1.000000,116.000000,106.000000,102.000000,100.000000,13.000000,13.000000,13.000000,11.000000,11.000000,11.000000,10.000000,11.000000,9.000000,10.000000,1.000000,12.900000,-9999.000000
75%,51153.250000,2.000000,1.000000,20.085000,1.000000,91.000000,119.000000,119.000000,117.000000,24.000000,19.000000,8.000000,4.000000,1.000000,4.000000,14.000000,5.000000,10.000000,3.000000,1.000000,11.000000,4.000000,14.000000,8.000000,1.000000,90.000000,10.250000,15.000000,27.000000,16.00000,15.000000,17.500000,32.000000,0.000000,14.000000,13.000000,15.000000,95.250000,15.000000,13.000000,15.250000,95.00000,13.000000,14.000000,16.000000,93.250000,281.000000,92.000000,1.000000,125.000000,116.000000,110.000000,107.500000,14.500000,14.000000,15.000000,13.000000,12.000000,12.500000,12.500000,12.000000,10.500000,12.000000,2.000000,14.440000,18.817500
max,51607.000000,2.000000,4.000000,64.000000,2.000000,100.000000,148.000000,180.000000,157.000000,30.000000,26.000000,13.000000,5.000000,1.000000,4.000000,22.000000,8.000000,14.000000,8.000000,1.000000,20.000000,8.000000,28.000000,10.000000,2.000000,164.000000,18.000000,29.000000,51.000000,29.00000,25.000000,37.000000,42.000000,1.000000,19.000000,23.000000,21.000000,138.000000,23.000000,20.000000,21.000000,127.00000,20.000000,19.000000,22.000000,138.000000,469.000000,131.000000,2.000000,144.000000,137.000000,126.000000,131.000000,17.000000,18.000000,17.000000,19.000000,15.000000,19.000000,17.000000,14.000000,15.000000,16.000000,2.000000,17.940000,35.430000

In [4]:
fenotipos.shape

(1112, 74)

In [5]:
fenotipos['SEX'].value_counts()

SEX
1    948
2    164
Name: count, dtype: int64

Vemos que os dados do sexo biológico estão bastante desbalanceados entre "1" e "2" (que devem ser "masculino" e "feminino", respectivamente).

In [10]:
pd.set_option('display.max_rows', None)
fenotipos.isnull().sum()

SITE_ID                               0
SUB_ID                                0
DX_GROUP                              0
DSM_IV_TR                             0
AGE_AT_SCAN                           0
SEX                                   0
HANDEDNESS_CATEGORY                 315
HANDEDNESS_SCORES                   742
FIQ                                  35
VIQ                                 177
PIQ                                 159
FIQ_TEST_TYPE                       165
VIQ_TEST_TYPE                       278
PIQ_TEST_TYPE                       259
ADI_R_SOCIAL_TOTAL_A                700
ADI_R_VERBAL_TOTAL_BV               700
ADI_RRB_TOTAL_C                     700
ADI_R_ONSET_TOTAL_D                 781
ADI_R_RSRCH_RELIABLE                701
ADOS_MODULE                         577
ADOS_TOTAL                          670
ADOS_COMM                           695
ADOS_SOCIAL                         695
ADOS_STEREO_BEHAV                   734
ADOS_RSRCH_RELIABLE                 732
ADOS_GOTHAM_SOCAFFECT               795
ADOS_GOTHAM_RRB                     795
ADOS_GOTHAM_TOTAL                   795
ADOS_GOTHAM_SEVERITY                795
SRS_VERSION                         843
SRS_RAW_TOTAL                       707
SRS_AWARENESS                      1048
SRS_COGNITION                      1048
SRS_COMMUNICATION                  1048
SRS_MOTIVATION                     1048
SRS_MANNERISMS                     1048
SCQ_TOTAL                           969
AQ_TOTAL                           1054
COMORBIDITY                        1048
CURRENT_MED_STATUS                  295
MEDICATION_NAME                     955
OFF_STIMULANTS_AT_SCAN              971
VINELAND_RECEPTIVE_V_SCALED         928
VINELAND_EXPRESSIVE_V_SCALED        928
VINELAND_WRITTEN_V_SCALED           928
VINELAND_COMMUNICATION_STANDARD     928
VINELAND_PERSONAL_V_SCALED          928
VINELAND_DOMESTIC_V_SCALED          928
VINELAND_COMMUNITY_V_SCALED         928
VINELAND_DAILYLVNG_STANDARD         928
VINELAND_INTERPERSONAL_V_SCALED     928
VINELAND_PLAY_V_SCALED              928
VINELAND_COPING_V_SCALED            928
VINELAND_SOCIAL_STANDARD            928
VINELAND_SUM_SCORES                 928
VINELAND_ABC_STANDARD               928
VINELAND_INFORMANT                  928
WISC_IV_VCI                        1057
WISC_IV_PRI                        1057
WISC_IV_WMI                        1057
WISC_IV_PSI                        1057
WISC_IV_SIM_SCALED                 1057
WISC_IV_VOCAB_SCALED               1057
WISC_IV_INFO_SCALED                1057
WISC_IV_BLK_DSN_SCALED             1057
WISC_IV_PIC_CON_SCALED             1057
WISC_IV_MATRIX_SCALED              1057
WISC_IV_DIGIT_SPAN_SCALED          1057
WISC_IV_LET_NUM_SCALED             1057
WISC_IV_CODING_SCALED              1057
WISC_IV_SYM_SCALED                 1057
EYE_STATUS_AT_SCAN                    0
AGE_AT_MPRAGE                      1011
BMI                                 898
dtype: int64

O conjunto de dados tem uma quantidade bastante expressiva de dados faltantes, mas essa ausência de dados está concentrada nas colunas dos testes neuropsicológicos, pois cada ponto de coleta escolheu o seu próprio conjunto de testes para avaliar o diagnóstico de TEA nos voluntários.